### ISSUE TITLE
Compile with ROOT first

### ISSUE THREAD

**Issue by fcpenha** [alisw/crmc#2]
When I try running tests such as 

```
bin/crmc -m 6 -p 1.e3 -P 0 -i 2212 -I 70140 -n 10000 -f /home/crmc/distr-fcpenha/out/test.root -o root
```

I get the message 

```
Compile with ROOT first
```

**Comment by ktf** [comment]
@qgp any reason you did not compile with ROOT support?

**Comment by qgp** [comment]
Because then we depend on ROOT and cannot change versions. Using HepMC output there is no need for the ROOT interface. Unless there is a real requirement for the ROOT interface, I would prefer not to have the dep, such that we stay more flexible. If there is a requirement, we can still play the trick of running two processes but it gets more complicated.

@fcpenha: what's the use case of this?

Cheers,
   Jochen

**Comment by fcpenha** [comment]
I need root tree files because they are input for another code. This code makes an interface with Python and counts particles and so on. It worked fine before, when collaborators provided me this kind of output from crmc.  

@qgp : I cannot change the strategy due to time constraints. It would be really useful to me learning the trick that you mentioned. Thanks.

**Comment by qgp** [comment]
We maintain an installation that serves the general purposes of the collaboration, so we have to understand if this is a common use case or not. While locally you can install whatever you want, for the cvmfs installation there are other considerations on common usability. I understand that you have a personal need now for a ROOT-linked version of cvmfs but it's not clear to me that this is an ALICE-general requirement and that we should change how we build the software for cvmfs.

PS: The trick I mentioned would allow to run different versions of CRMC even though they depend on another AliPhysics/AliRoot/ROOT version than used for the analysis (in case of HepMC output). It does not add ROOT capabilities if CRMC was built without.

**Comment by fcpenha** [comment]
Ok, I realize now I may be in the wrong place. The previous issue I opened already raised a flag. I am using CRMC outside Alice environment. My issues in principle are completely independent of that. I am following the CRMC installation procedure described in the README file, because I only need CRMC and its dependencies (cmake, boost, fastjet, hepmc, root). I am sorry for not making it clear before. Given that, if you still can help me, should I change something in the installation procedure? I thought FindRoot.cmake was already making sure CRMC finds ROOT.

**Comment by fcpenha** [comment]
@qgp  @ktf I am truly sorry for wasting your time. I am closing the issue, because it is out of the context of Alice.

**Comment by ktf** [comment]
No worries.
